### ISSUE TITLE
Failed rspec tests: block_spec.rb

### ISSUE THREAD

**Issue by did** [tigerlily/solid#4]
hi guys,

I've got that error when running the tests suite:

```
1) Solid::Block#display yielding should render the block content
 Failure/Error: yield
 NoMethodError:
   undefined method `has_interrupt?' for {"condition"=>true}:Hash
 # ./lib/solid/block.rb:8:in `block (2 levels) in render'
 # ./spec/solid/block_spec.rb:7:in `display'
 # ./lib/solid/block.rb:7:in `block in render'
 # ./lib/solid/element.rb:20:in `with_context'
 # ./lib/solid/block.rb:6:in `render'
 # ./spec/solid/block_spec.rb:26:in `block (3 levels) in <top (required)>'
```

In the line 26, there should be instead:

```
 subject.render(Liquid::Context.new('condition' => true))
```

Hope it helps, thanks.

**Comment by byroot** [comment]
Thanks for the report, it's fixed on master.

There was a bunch of activity on Liquid lately, I'll try to understand what happened.

**Comment by did** [comment]
You're welcome !
